export const AuditEvent = Object.freeze({
  AUTH_LOGIN:           "AUTH_LOGIN",
  AUTH_LOGOUT:          "AUTH_LOGOUT",
  POWER_GIVEN:          "POWER_GIVEN",
  POWER_RECOVERED:      "POWER_RECOVERED",
  POWER_TRANSFERRED:    "POWER_TRANSFERRED",
  VOTE_VPC_SUBMITTED:   "VOTE_VPC_SUBMITTED",
  VOTE_LIVE_SUBMITTED:  "VOTE_LIVE_SUBMITTED",
  VOTE_MANUAL_SYNDIC:   "VOTE_MANUAL_SYNDIC",
  ATTENDANCE_ARRIVED:   "ATTENDANCE_ARRIVED",
  ATTENDANCE_LEFT:      "ATTENDANCE_LEFT",
});
